### ISSUE TITLE
[3Di]: dem edit through levee causes water on other side of the levee when dem edit is lower (production)

### ISSUE THREAD

**Issue by GeOdin** [nens/servicedesk-issue-only#119]
### Incident Type

Error

### 3Di component

Livesite

### What happened?

When I created a DEM edit through 1 part of the levee, water also turned up on the other side of the levee.

### How to Reproduce?

Open the v2_bergermeer_with_grndwtr model
Create a (-20) DEM edit from within a calculation cell (rekencel) through one side of the levee (dijk)  without touching or going through a calculation cell that goes through the other side of the levee.
Water is not only shown on the side with the dem edit, but also on the other side of the levee.
If the input of the dem edit is -2, this does not happen.

### What did you expect and what was the actual result?

Creating a dem edit through one side of a levee also caused water to show on the other side of the model. I didnot wxpect that water would also shown on the other side of the model.
It also happened for -20 and did not seem to happen for -2.
I do not think the dem edit value would have an effect on this.

### Add screenshots, video's etc

DEM edit -20
![20221117 - 3di live - water outside djk when only changing dem inside](https://user-images.githubusercontent.com/13179397/202504146-6f86a4f5-b34e-4232-9d3a-d3d67d31366c.png)

DEM edit -2
![20221117 - 3di live - water not outside djk when only changing dem through other levee but lower height](https://user-images.githubusercontent.com/13179397/202504256-aa00f654-77f6-46f0-9281-7015e8beca50.png)

### Additional info

Found on Chrome, but probably also on other borwsers.

Good luck!

**Comment by GeOdin** [comment]
Occured today again with relative height -20 and these error messages:

`WebsocketMiddleware.tsx:327 Caught websocket error message: Object
(anonymous) @ WebsocketMiddleware.tsx:327
WebsocketMiddleware.tsx:327 Caught websocket error message: Object
(anonymous) @ WebsocketMiddleware.tsx:327
WebsocketMiddleware.tsx:327 Caught websocket error message: Objecterror: truemeta: {timestamp: Wed Nov 23 2022 12:05:03 GMT+0100 (Midden-Europese standaardtijd), message: 'Socket connection not initialized. Dispatch WEBSOCKET_CONNECT first', name: 'Error', originalAction: {…}}payload: Error: Socket connection not initialized. Dispatch WEBSOCKET_CONNECT first
    at eval (webpack:///./src/ReduxWebSocket.ts?:101:15)
    at eval (webpack:///./src/createMiddleware.ts?:63:15)
    at eval (webpack:///./src/createMiddleware.ts?:70:16)
    at eval (webpack:///./src/createMiddleware.ts?:70:16)
    at https://www.3di.live/static/js/2.2c8ae6f0.chunk.js:2:904406
    at dispatch (https://www.3di.live/static/js/2.2c8ae6f0.chunk.js:2:247990)
    at https://www.3di.live/static/js/main.f05b9844.chunk.js:1:452415
    at https://www.3di.live/static/js/2.2c8ae6f0.chunk.js:2:904397
    at https://www.3di.live/static/js/main.f05b9844.chunk.js:1:452359
    at https://www.3di.live/static/js/main.f05b9844.chunk.js:1:451552type: "WATERDEPTHS::ERROR"[[Prototype]]: Object
(anonymous) @ WebsocketMiddleware.tsx:327
existingEvents.ts:264 Receiving RasterEdit model message with action create
WebsocketMiddleware.tsx:327 Caught websocket error message: {type: 'WATERDEPTHS::ERROR', meta: {…}, error: true, payload: DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at eval (webp…}error: truemeta: {timestamp: Wed Nov 23 2022 12:06:03 GMT+0100 (Midden-Europese standaardtijd), message: "Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.", name: 'InvalidStateError', originalAction: {…}}payload: DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at eval (webpack:///./src/ReduxWebSocket.ts?:96:27)
    at eval (webpack:///./src/createMiddleware.ts?:63:15)
    at eval (webpack:///./src/createMiddleware.ts?:70:16)
    at eval (webpack:///./src/createMiddleware.ts?:70:16)
    at https://www.3di.live/static/js/2.2c8ae6f0.chunk.js:2:904406
    at https://www.3di.live/static/js/main.f05b9844.chunk.js:1:198959type: "WATERDEPTHS::ERROR"[[Prototype]]: Object
(anonymous) @ WebsocketMiddleware.tsx:327
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
dispatch @ redux.js:659
eval @ createMiddleware.ts:65
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
(anonymous) @ index.js:20
(anonymous) @ WebsocketMiddleware.tsx:607
Promise.then (async)
(anonymous) @ WebsocketMiddleware.tsx:598
Promise.then (async)
Ri @ WebsocketMiddleware.tsx:593
(anonymous) @ WebsocketMiddleware.tsx:547
WebsocketMiddleware.tsx:327 Caught websocket error message: {type: 'WATERDEPTHS::ERROR', meta: {…}, error: true, payload: DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at eval (webp…}
(anonymous) @ WebsocketMiddleware.tsx:327
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
dispatch @ redux.js:659
eval @ createMiddleware.ts:65
eval @ createMiddleware.ts:70
eval @ createMiddleware.ts:70
(anonymous) @ index.js:20
(anonymous) @ WebsocketMiddleware.tsx:624
WebsocketMiddleware.tsx:327 Caught websocket error message: {type: 'WATERDEPTHS::ERROR', meta: {…}, error: true, payload: DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at eval (webp…}`
![20221122 - 3di live - water on wrong side of the levee chrome relative -20](https://user-images.githubusercontent.com/13179397/203532751-2a582863-92ea-4825-8fda-b52db5e8350a.png)

**Comment by GeOdin** [comment]
Might be related to
https://github.com/nens/servicedesk-issue-only/issues/125
