### ISSUE TITLE
[3Di]: No water in negative DEM edit after creating negative DEM edit between levees (dijken) with rekenpunt within (calculation cell?) (production)

### ISSUE THREAD

**Issue by GeOdin** [nens/servicedesk-issue-only#124]
### Incident Type

Error

### 3Di component

Livesite

### What happened?

When I created a negative DEM edit between levees, no water was shown in the DEM edit.

### How to Reproduce?

Open a model on the live site, for example v2_bergermeer - v2_bergermeer_with_grndwtr (1) #111 with template with_grndwtr
Create a negative DEM edit within a calculation cell (rekencell) entirely within levees (dijken)
No water is shown in the DEM edit.
This goes for the absolute and relative dem edit and I tested it with the values -2 and -20, but I think other negative value would give similar results.

### What did you expect and what was the actual result?

I expected water to show in the DEM edit. (The DEM edit becoming blue)

### Absolute height -2
![20221122  - 3di - geen water in rekenpunt absolute height -2 chrome](https://user-images.githubusercontent.com/13179397/203527660-38cd47de-8dd2-4ab9-a00d-20ed1cd58f10.png)

### Absolute height -20
![20221122  - 3di - geen water in rekenpunt absolute height -20 chrome](https://user-images.githubusercontent.com/13179397/203527663-c5ab8583-6f5f-4d41-8aa5-2b984bc587e3.png)

### Relative height -20
![20221122  - 3di - geen water in rekenpunt relatieve height -20 chrome](https://user-images.githubusercontent.com/13179397/203527666-235704e1-4235-40b4-a0bf-c1e3e1531bcd.png)

### Relative height -2
![20221122  - 3di - geen water in rekenpunt relative height -2 chrome](https://user-images.githubusercontent.com/13179397/203527667-2c68553b-0436-46cd-aa71-640b5e2b2b99.png)

### Relevant log output

```shell
WebsocketMiddleware.tsx:327 Caught websocket error message: Objecterror: truemeta: {timestamp: Wed Nov 23 2022 11:32:41 GMT+0100 (Midden-Europese standaardtijd), message: 'Socket connection not initialized. Dispatch WEBSOCKET_CONNECT first', name: 'Error', originalAction: {…}}payload: Error: Socket connection not initialized. Dispatch WEBSOCKET_CONNECT first
    at eval (webpack:///./src/ReduxWebSocket.ts?:101:15)
    at eval (webpack:///./src/createMiddleware.ts?:63:15)
    at eval (webpack:///./src/createMiddleware.ts?:70:16)
    at eval (webpack:///./src/createMiddleware.ts?:70:16)
    at https://www.3di.live/static/js/2.2c8ae6f0.chunk.js:2:904406
    at dispatch (https://www.3di.live/static/js/2.2c8ae6f0.chunk.js:2:247990)
    at https://www.3di.live/static/js/main.f05b9844.chunk.js:1:452415
    at https://www.3di.live/static/js/2.2c8ae6f0.chunk.js:2:904397
    at https://www.3di.live/static/js/main.f05b9844.chunk.js:1:452359
    at https://www.3di.live/static/js/main.f05b9844.chunk.js:1:451552message: "Socket connection not initialized. Dispatch WEBSOCKET_CONNECT first"stack: "Error: Socket connection not initialized. Dispatch WEBSOCKET_CONNECT first\n    at eval (webpack:///./src/ReduxWebSocket.ts?:101:15)\n    at eval (webpack:///./src/createMiddleware.ts?:63:15)\n    at eval (webpack:///./src/createMiddleware.ts?:70:16)\n    at eval (webpack:///./src/createMiddleware.ts?:70:16)\n    at https://www.3di.live/static/js/2.2c8ae6f0.chunk.js:2:904406\n    at dispatch (https://www.3di.live/static/js/2.2c8ae6f0.chunk.js:2:247990)\n    at https://www.3di.live/static/js/main.f05b9844.chunk.js:1:452415\n    at https://www.3di.live/static/js/2.2c8ae6f0.chunk.js:2:904397\n    at https://www.3di.live/static/js/main.f05b9844.chunk.js:1:452359\n    at https://www.3di.live/static/js/main.f05b9844.chunk.js:1:451552"[[Prototype]]: Objecttype: "WATERDEPTHS::ERROR"[[Prototype]]: Object
(anonymous) @ WebsocketMiddleware.tsx:327
3existingEvents.ts:264 Receiving RasterEdit model message with action create
```

### Additional info

I tested this on Chrome.

Good luck! :)

**Comment by GeOdin** [comment]
Rekencel should be rekenpunt. I think the English was calculation cell, but not sure so added the ? behind calculation cell.
