### ISSUE TITLE
[3Di]: Create forecast rain for period without data could have better error message (production)

### ISSUE THREAD

**Issue by GeOdin** [nens/servicedesk-issue-only#148]
### Incident Type

Feedback

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

Livesite

### What happened?

When I created a forecast rain for a period without rain gave the error message:
Failed to send request.

Maybe it would be a better error message when it was a bit more specific.
For example:

Failed to send request because there is no data for the selected period

### How to Reproduce?

Go to the live site 3Di.live
Start a model for example v2_bergermeer_with_grndwtr #111 template with_grndwtr
Go to the rain tool
Select Forecast rain
Select a period where there is no rain (Preview not available for raster is shown in graph below)
Press create
An error message appears below the graph 'Failed to send request'

### What did you expect and what was the actual result?

I expected a more detailed error message, so that it would be more clear what the user can improve.

### Add screenshots, video's etc

![20230206 - 3di live - forecast rain - no data create could have better error message](https://user-images.githubusercontent.com/13179397/217196491-b4892c6b-c77f-4f6c-9220-fed80e123e70.png)
![20230206 - 3di live - forecast rain - no data create could have better error message2](https://user-images.githubusercontent.com/13179397/217196498-282c1c8b-f265-49aa-a267-655949854154.png)

### Relevant log output

```shell
main.e6feee0fc806cdb6.js:2          GET https://demo.lizard.net/api/v4/rasters/36a184ee-8494-4374-886d-043466f9b132/zonal/?zonal_statistic=mean&temporal_statistic=sum&frequency=D&geom=POLYGON((+4.655663106692435+52.59085747474975,+4.808619109451917+52.59085747474975,+4.808619109451917+52.697177258887294,+4.655663106692435+52.697177258887294,+4.655663106692435+52.59085747474975))&start=2023-02-07T07:41:20Z&stop=2023-02-14T08:41:20Z 404
queryFn @ main.e6feee0fc806cdb6.js:2
fetchFn @ main.e6feee0fc806cdb6.js:2
u @ main.e6feee0fc806cdb6.js:2
c @ main.e6feee0fc806cdb6.js:2
e.fetch @ main.e6feee0fc806cdb6.js:2
n.executeFetch @ main.e6feee0fc806cdb6.js:2
n.fetch @ main.e6feee0fc806cdb6.js:2
n.refetch @ main.e6feee0fc806cdb6.js:2
e.onFocus @ main.e6feee0fc806cdb6.js:2
(anonymous) @ main.e6feee0fc806cdb6.js:2
(anonymous) @ main.e6feee0fc806cdb6.js:2
e.batch @ main.e6feee0fc806cdb6.js:2
n.onFocus @ main.e6feee0fc806cdb6.js:2
(anonymous) @ main.e6feee0fc806cdb6.js:2
(anonymous) @ main.e6feee0fc806cdb6.js:2
n.onFocus @ main.e6feee0fc806cdb6.js:2
(anonymous) @ main.e6feee0fc806cdb6.js:2
n @ main.e6feee0fc806cdb6.js:2
main.e6feee0fc806cdb6.js:2          GET https://demo.lizard.net/api/v4/rasters/36a184ee-8494-4374-886d-043466f9b132/zonal/?zonal_statistic=mean&temporal_statistic=sum&frequency=H&geom=POLYGON((+4.655663106692435+52.59085747474975,+4.808619109451917+52.59085747474975,+4.808619109451917+52.697177258887294,+4.655663106692435+52.697177258887294,+4.655663106692435+52.59085747474975))&start=2023-02-07T08:38:16Z&stop=2023-02-14T08:38:16Z 404
x.enabled @ main.e6feee0fc806cdb6.js:2
fetchFn @ main.e6feee0fc806cdb6.js:2
u @ main.e6feee0fc806cdb6.js:2
c @ main.e6feee0fc806cdb6.js:2
e.fetch @ main.e6feee0fc806cdb6.js:2
n.executeFetch @ main.e6feee0fc806cdb6.js:2
n.fetch @ main.e6feee0fc806cdb6.js:2
n.refetch @ main.e6feee0fc806cdb6.js:2
e.onFocus @ main.e6feee0fc806cdb6.js:2
(anonymous) @ main.e6feee0fc806cdb6.js:2
(anonymous) @ main.e6feee0fc806cdb6.js:2
e.batch @ main.e6feee0fc806cdb6.js:2
n.onFocus @ main.e6feee0fc806cdb6.js:2
(anonymous) @ main.e6feee0fc806cdb6.js:2
(anonymous) @ main.e6feee0fc806cdb6.js:2
n.onFocus @ main.e6feee0fc806cdb6.js:2
(anonymous) @ main.e6feee0fc806cdb6.js:2
n @ main.e6feee0fc806cdb6.js:2
main.e6feee0fc806cdb6.js:2          POST https://api.3di.live/v3/simulations/114058/events/rain/rasters/lizard/ 400
fetchApi @ main.e6feee0fc806cdb6.js:2
request @ main.e6feee0fc806cdb6.js:2
await in request (async)
simulationsEventsRainRastersLizardCreateRaw @ main.e6feee0fc806cdb6.js:2
simulationsEventsRainRastersLizardCreate @ main.e6feee0fc806cdb6.js:2
onClick @ main.e6feee0fc806cdb6.js:2
Ot @ main.e6feee0fc806cdb6.js:2
Ut @ main.e6feee0fc806cdb6.js:2
(anonymous) @ main.e6feee0fc806cdb6.js:2
Ni @ main.e6feee0fc806cdb6.js:2
ji @ main.e6feee0fc806cdb6.js:2
(anonymous) @ main.e6feee0fc806cdb6.js:2
uu @ main.e6feee0fc806cdb6.js:2
Ct @ main.e6feee0fc806cdb6.js:2
Hi @ main.e6feee0fc806cdb6.js:2
We @ main.e6feee0fc806cdb6.js:2
Ve @ main.e6feee0fc806cdb6.js:2
main.e6feee0fc806cdb6.js:2 sending rain request failed with request {simulationPk: '114058', data: {…}}data: duration: 604799offset: 0referenceUuid: "36a184ee-8494-4374-886d-043466f9b132"startDatetime: Tue Feb 07 2023 09:38:16 GMT+0100 (Central European Standard Time)[[Prototype]]: Objectunits: "mm/h"[[Prototype]]: ObjectsimulationPk: "114058"[[Prototype]]: Object error: ResponseError: Response returned an error code
    at Yc.request (main.e6feee0fc806cdb6.js:2:202145)
    at async Yc.simulationsEventsRainRastersLizardCreateRaw (main.e6feee0fc806cdb6.js:2:542149)
    at async Yc.simulationsEventsRainRastersLizardCreate (main.e6feee0fc806cdb6.js:2:542447)
(anonymous) @ main.e6feee0fc806cdb6.js:2
Promise.catch (async)
onClick @ main.e6feee0fc806cdb6.js:2
Ot @ main.e6feee0fc806cdb6.js:2
Ut @ main.e6feee0fc806cdb6.js:2
(anonymous) @ main.e6feee0fc806cdb6.js:2
Ni @ main.e6feee0fc806cdb6.js:2
ji @ main.e6feee0fc806cdb6.js:2
(anonymous) @ main.e6feee0fc806cdb6.js:2
uu @ main.e6feee0fc806cdb6.js:2
Ct @ main.e6feee0fc806cdb6.js:2
Hi @ main.e6feee0fc806cdb6.js:2
We @ main.e6feee0fc806cdb6.js:2
Ve @ main.e6feee0fc806cdb6.js:2
```

### Additional info

The error messages are 400/404 errors, probably because there is no data for the requested time period.

Good luck! :)

**Comment by GeOdin** [comment]
Ps works when there is data:


![20230206 - 3di live - chrome - forecast request not send - because of no data questionmark but works when there is data](https://user-images.githubusercontent.com/13179397/217198634-ba60bbf6-62ee-48f0-8350-9b55813a3298.png)
![20230206 - 3di live - chrome - forecast request not send - because of no data questionmark but works when there is data 2](https://user-images.githubusercontent.com/13179397/217198627-d00801d4-f0fa-449c-90c7-47cc9e2c96ca.png)
